# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.order = 'random'
end

require 'sinatra'
require 'modules/helpers'
require 'modules/controllers'
require 'modules/backend'
require 'server/command_line_parser'
require 'modules/security/authorization'
require 'modules/security/authentication'

include RedisMonitor
include RedisMonitor::Controllers
include RedisMonitor::Errors
